project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: https://api.crowdin.com

preserve_hierarchy: true

files:
- source: src/locales/en/*.json
  translation: src/locales/%two_letters_code%/%file_name%
  update_option: update_as_unapproved
  skip_untranslated_strings: true
  export_only_approved: true
