name: Push localization strings to Crowdin

on:
  push:
    branches: [ master ]
    paths:
    - 'src/locales/**'

jobs:
  push-to-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push
        uses: crowdin/github-action@1.4.7
        with:
          upload_sources: true
          crowdin_branch_name: {{ env.GITHUB_REF_NAME }}
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
